"use client";

import { useEffect, useRef } from "react";

/**
 * Swagger UI for the combined OpenAPI 3.1 spec.
 * Spec is generated by `python3 scripts/generate_openapi.py` into /openapi/openapi.yaml.
 */
export default function SwaggerPage() {
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    let cancelled = false;
    const cssId = "swagger-ui-css";
    if (!document.getElementById(cssId)) {
      const link = document.createElement("link");
      link.id = cssId;
      link.rel = "stylesheet";
      link.href = "https://unpkg.com/swagger-ui-dist@5.17.14/swagger-ui.css";
      document.head.appendChild(link);
    }

    void (async () => {
      // Dynamic script load avoids bundling swagger-ui into the Next app.
      await new Promise<void>((resolve, reject) => {
        if ((window as unknown as { SwaggerUIBundle?: unknown }).SwaggerUIBundle) {
          resolve();
          return;
        }
        const script = document.createElement("script");
        script.src = "https://unpkg.com/swagger-ui-dist@5.17.14/swagger-ui-bundle.js";
        script.onload = () => resolve();
        script.onerror = () => reject(new Error("Failed to load Swagger UI"));
        document.body.appendChild(script);
      });
      if (cancelled || !ref.current) return;
      const SwaggerUIBundle = (
        window as unknown as {
          SwaggerUIBundle: (opts: Record<string, unknown>) => unknown;
        }
      ).SwaggerUIBundle;
      SwaggerUIBundle({
        url: "/openapi/openapi.yaml",
        dom_id: "#zatgo-swagger-root",
        deepLinking: true,
        presets: [(window as unknown as { SwaggerUIBundle: { presets: { apis: unknown } } }).SwaggerUIBundle.presets.apis],
      });
    })().catch((err) => {
      if (ref.current) {
        ref.current.textContent = err instanceof Error ? err.message : "Swagger failed to load";
      }
    });

    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <div className="space-y-4">
      <div>
        <h1 className="text-2xl font-semibold">Swagger UI</h1>
        <p className="text-sm text-[var(--color-muted-foreground)]">
          Combined Frappe whitelist API (`openapi.yaml`). Regenerate with{" "}
          <code className="rounded bg-[var(--color-muted)] px-1">python3 scripts/generate_openapi.py</code>.
        </p>
      </div>
      <div id="zatgo-swagger-root" ref={ref} className="min-h-[70vh] rounded-[var(--radius-lg)] bg-white" />
    </div>
  );
}
